"""Test harness for the Fusion-Essentials MCP tools.

The tools under ``commands/mcpServer/tools/`` are written for a *live* Fusion
session: each one does ``import adsk.core`` and runs ``app =
adsk.core.Application.get()`` at module top level, and reaches Fusion geometry
through ``adsk.fusion``. To unit-test their pure logic outside Fusion we:

  1. Inject lightweight mock ``adsk`` modules into ``sys.modules`` BEFORE any
     tool is imported (so the module-top ``Application.get()`` succeeds).
  2. Load a single tool module in isolation — without running
     ``commands/__init__.py`` (which builds Fusion UI panels) or
     ``tools/__init__.py`` (which imports every tool module, most needing adsk).

``load_tool("model_inspect")`` does both and returns the module so a
test can call its ``handler(...)`` and private helpers directly.

The mocks here are deliberately small: they implement only what a tool actually
touches. Extend them as you add tests for more tools — that is the intended
workflow.
"""

import contextlib
import importlib.util
import json
import math
import os
import sys
import types
from unittest.mock import Mock

import pytest

# Measured adsk API facts, GENERATED by tests/live/measure_api.py against live Fusion. The
# mocks below are populated from these values - measurement, not hand-typed claims.
import live_api_facts as _api_facts


@contextlib.contextmanager
def _no_bytecode():
    """Suppress .pyc writing for the source THIS harness loads (see load_tool/load_mcp_server).

    The loaders below spec-load repo source directly, so Python would write __pycache__/*.pyc next
    to it. That bytecode is validated against the source's mtime at ONE-SECOND resolution plus its
    size, so editing-then-restoring a tool inside one second - what a break/confirm-red/restore
    regression check does - can leave a .pyc that masks the restored source.

    The suppression is scoped rather than process-wide because pytest gates its assertion-rewrite
    cache on the SAME flag (_pytest/assertion/rewrite.py: `write = not sys.dont_write_bytecode`),
    and a process-wide True makes every test module re-parse and re-rewrite on every run. Nothing
    pytest rewrites is imported inside this block: it wraps the harness's own imports of the
    adsk-free server packages and its spec-loads of tool/server modules.
    """
    saved = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        yield
    finally:
        sys.dont_write_bytecode = saved


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMANDS_DIR = os.path.join(REPO_ROOT, "commands")
TOOLS_DIR = os.path.join(COMMANDS_DIR, "mcpServer", "tools")


# ── adsk mock installation ─────────────────────────────────────────────────

class _StrictEnum:
    """One measured adsk enum family. Accessing a member that was NOT measured against live Fusion
    raises AttributeError, exactly as the live enum does. Tools legitimately probe with
    getattr(Enum, name, None) for version-dependent members, and that still returns the default."""

    def __init__(self, family, members):
        self._family = family
        for member, value in members.items():
            setattr(self, member, value)

    def __getattr__(self, name):
        known = ", ".join(sorted(k for k in vars(self) if not k.startswith("_")))
        raise AttributeError(
            f"adsk.{self._family} has no member '{name}' - it does not exist in Fusion "
            f"{_api_facts.FUSION_VERSION}. Measured members: {known}. If '{name}' is real, add a "
            "measurement row to tests/live/measure_api.py and regenerate live_api_facts.py.")

    def __repr__(self):
        return f"<measured adsk.{self._family}>"


def install_mock_adsk():
    """Inject mock ``adsk`` / ``adsk.core`` / ``adsk.fusion`` into sys.modules.

    Returns ``(adsk, core, fusion)``. ``core``/``fusion`` are ``Mock`` objects,
    so any attribute a tool reads that we haven't explicitly modelled returns a
    child Mock rather than raising — convenient, but it means a test must assert
    on concrete values to actually pin behaviour down (a Mock is truthy and not
    ``None``). The type classes a tool uses for ``isinstance`` / ``.cast`` /
    ``type(x).__name__`` checks ARE modelled below, because those drive real
    branching.

    IDEMPOTENT: gen_manifest.py/gen_wiring.py call this again at their own import
    time so they work standalone (outside pytest) too - they rely on a second call
    being a no-op when a mock is already installed. A real re-install here would
    replace sys.modules['adsk'/'adsk.fusion'/...] with BRAND NEW objects; any module
    already loaded (e.g. _inputs.py, cached tool modules) keeps its OLD reference,
    so a later isinstance/.cast check would compare against the wrong generation
    of mock and fail in a way that depends on collection order.
    """
    existing = sys.modules.get("adsk")
    if (isinstance(existing, types.ModuleType)
            and sys.modules.get("adsk.fusion") is getattr(existing, "fusion", None)
            and sys.modules.get("adsk.core") is getattr(existing, "core", None)):
        return existing, existing.core, existing.fusion

    core = Mock()
    app = Mock()
    # Tools commonly tack `"active_document": app.activeDocument.name` onto a
    # payload that then gets json.dumps'd. A bare Mock().name is itself a Mock
    # (not JSON-serializable), so give the stock app a real string name. Tests
    # that care about document state override app.activeDocument explicitly.
    app.activeDocument.name = "TestDoc"
    app.version = "0.0.0-test"
    core.Application.get.return_value = app

    # CustomEventHandler is SUBCLASSED (task_manager's TaskEventHandler) - an auto-created Mock
    # attribute as a base class produces mock-flavored class machinery whose constructor cannot be
    # called normally, so the base must be a real (empty) class.
    core.CustomEventHandler = type("CustomEventHandler", (), {"__init__": lambda self: None})

    fusion = Mock()
    # Design.cast(product) fetches the active design. Model it as a
    # pass-through: whatever the test puts on app.activeProduct comes back.
    fusion.Design = Mock()
    fusion.Design.cast = Mock(side_effect=lambda x: x)

    # adsk.cam is needed by the CAM tools.
    cam = Mock()
    # Tools cast raw collection items with adsk.cam.Operation.cast(op) and skip
    # anything that casts to None. A bare Mock().cast returns a truthy Mock, which
    # would mask that filter; make cast a pass-through so a test's fake op (or a
    # real None) flows through unchanged.
    cam.Operation.cast = Mock(side_effect=lambda x: x)

    # adsk.drawing is needed by the drawing tools (drawing_create, drawing_export), which do
    # `import adsk.drawing` at module top - without it their import fails and the registry-wide
    # lints can't collect. A bare Mock covers the DrawingManager/DrawingExportManager surface.
    drawing = Mock()

    # Seed every measured enum family onto the mock namespaces, so comparison/branch code sees
    # the live integers without per-test hand-wiring. The drawing namespace gets the same strict
    # seeding, and its measured families now include the ones reached only by NAME through
    # _drawing_common.enum_value - SheetSizes, SheetOrientationTypes and DrawingStandardTypes - as
    # well as the ones referenced as literal adsk.drawing.<Family>: the harvester scans both, so
    # every family a drawing tool can read is measured here. Without that seeding they would be
    # fabricatable child Mocks, the exact silent-drop class the strict enums exist to refuse.
    ns = {"core": core, "fusion": fusion, "cam": cam, "drawing": drawing}
    for family, members in _api_facts.ENUMS.items():
        prefix, cls_name = family.split(".", 1)
        # A plain object, NOT the auto-created child Mock: a Mock invents any attribute asked of it,
        # so a member name that does not exist in live Fusion would return a fresh Mock, the tool
        # would set it on its input, and a test asserting `input.x == Enum.FabricatedName` would
        # compare that Mock to itself and PASS. _StrictEnum raises instead, like the live enum does.
        setattr(ns[prefix], cls_name, _StrictEnum(family, members))

    adsk = types.ModuleType("adsk")
    adsk.core = core
    adsk.fusion = fusion
    adsk.cam = cam
    adsk.drawing = drawing

    sys.modules["adsk"] = adsk
    sys.modules["adsk.core"] = core
    sys.modules["adsk.fusion"] = fusion
    sys.modules["adsk.cam"] = cam
    sys.modules["adsk.drawing"] = drawing
    return adsk, core, fusion


def load_tool(module_name):
    """Import one tool module in isolation, with mocked adsk already installed.

    Skips ``commands/__init__.py`` (Fusion UI side effects) and
    ``tools/__init__.py`` (imports every tool) by putting ``commands/`` on the
    path, importing only the cheap ``mcpServer`` + ``mcp_primitives`` packages,
    stubbing ``mcpServer.tools`` as an empty package, then spec-loading the
    single requested module so its ``from ..mcp_primitives ...`` relative
    imports resolve.

    Everything it loads runs under ``_no_bytecode()``: the tool module itself, the ``from . import
    _common``/``_inputs`` chain its body triggers, and the mcp_primitives packages.
    """
    with _no_bytecode():
        if COMMANDS_DIR not in sys.path:
            sys.path.insert(0, COMMANDS_DIR)

        import mcpServer                  # noqa: F401  empty __init__, cheap
        import mcpServer.mcp_primitives   # noqa: F401  adsk-free, cheap

        if "mcpServer.tools" not in sys.modules:
            tools_pkg = types.ModuleType("mcpServer.tools")
            tools_pkg.__path__ = [TOOLS_DIR]
            tools_pkg.__package__ = "mcpServer"
            sys.modules["mcpServer.tools"] = tools_pkg

        full_name = f"mcpServer.tools.{module_name}"
        # Reuse an already-loaded module instead of re-execing it into a NEW object. This is essential
        # for the shared substrate (_common/_inputs): tools do `from . import _common`, binding whatever
        # _common object is in sys.modules at load time. Re-execing _common would create a SECOND
        # _common — a tool loaded earlier keeps pointing at the first while the conftest
        # snapshot/restore (and a later test's patch) act on the second, so a patch or restore made
        # through one is invisible through the other. One canonical module per name keeps the seam
        # single-identity; each test wires its own per-test state onto that one object
        # (install()/monkeypatch), so reusing it is safe.
        if full_name in sys.modules:
            return sys.modules[full_name]
        spec = importlib.util.spec_from_file_location(
            full_name, os.path.join(TOOLS_DIR, f"{module_name}.py")
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[full_name] = module
        spec.loader.exec_module(module)
        # Record the seams of everything that import just put in sys.modules - the module itself and
        # the substrate its `from . import _common`/`_inputs` chain pulled in - while they still hold
        # their as-imported values. See _capture_pristine_seams.
        _capture_pristine_seams()
        return module


def stub_tool_module(monkeypatch, module_name, stub):
    """Swap ``mcpServer.tools.<module_name>`` for ``stub`` at both seams a sibling module is reached
    through. Returns the stub.

    The two seams belong to DIFFERENT import forms, and each patch serves exactly one of them:

    * ``from . import <module_name>`` - the form a handler's deferred delegate import uses
      (``data_get``) - resolves through the tools PACKAGE ATTRIBUTE. ``_handle_fromlist`` checks
      ``hasattr(package, name)`` FIRST and skips the submodule import entirely when it holds, so
      the ATTRIBUTE patch is what routes this form, in either order. A genuine import elsewhere
      binds that attribute too (``doc_get`` binds ``_data_read``; ``mesh_edit`` binds
      ``mesh_ops``), and a sys.modules-only stub is then never consulted: the handler gets the real
      module and the stub goes silently inert while the test still passes or fails on what the real
      module does.
    * ``importlib.import_module(".<module_name>", __package__)`` at CALL time - what
      ``sketch_core._detail_engine`` and ``sys_api_doc``'s module walk do - reads SYS.MODULES and
      never the attribute, so the setitem is the only live seam for that shape.

    Both patches belong to ``monkeypatch``, so they unwind after the test - including the attribute,
    which is REMOVED again when the package did not carry it.
    """
    pkg = sys.modules.get("mcpServer.tools")
    if pkg is None:
        raise RuntimeError("stub_tool_module needs the tools package: call load_tool(...) first.")
    monkeypatch.setitem(sys.modules, f"mcpServer.tools.{module_name}", stub)
    monkeypatch.setattr(pkg, module_name, stub, raising=False)
    return stub


# Synthetic package root under which the REAL server modules are importable in tests.
_SERVER_PKG_ROOT = "feaddin"


def register_all_tools():
    """Load + register EVERY tool module against a fresh registry; return the registered Items.

    The one shared harness for wire-surface tests (shape + budget) - a single copy, so the two
    files cannot drift. Callers pair it with the conftest registry snapshot/restore (autouse),
    which undoes the global-registry mutation after each test."""
    names = [fn[:-3] for fn in sorted(os.listdir(TOOLS_DIR))
             if fn.endswith(".py") and not fn.startswith("_")]
    load_tool(names[0])                    # bootstraps the package path on first use
    from mcpServer.mcp_primitives import registry
    registry.reset_registry()
    for mod_name in names:
        mod = load_tool(mod_name)
        reg = getattr(mod, "register_tool", None)
        if callable(reg):
            reg()
    return registry.get_tools()


def load_tool_verify():
    """Import ``tests/live/tool_verify.py`` as a module and return it.

    The live sweep's tables (STEPS / EXCLUDED / PENDING) are plain data, so the offline lints read
    them without a Fusion - completeness against the registry, and which choices the steps send.
    One loader here rather than one per lint: the sweep's path moves as a unit."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "live", "tool_verify.py")
    with _no_bytecode():
        spec = importlib.util.spec_from_file_location("tool_verify", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
    return mod


def is_write_tool(item):
    """True when a registered Item DECLARES itself a write - ``annotations.read_only is False``.

    A missing annotation and ``read_only is None`` both answer False: a tool that never declared its
    write status is not a write tool for a lint's purposes, and test_write_status_annotations is the
    gate that no such tool exists."""
    ann = item.primitive.annotations
    return ann is not None and ann.read_only is False


def load_mcp_server():
    """Import the REAL server/mcp_server.py (plus task_manager) for wire-level tests.

    mcp_server.py lives four packages deep in the add-in (``<addin>.commands.mcpServer.server``)
    and imports ``....lib.fusion360utils`` relatively, so it cannot be imported through the flat
    ``mcpServer`` package load_tool uses. This builds a synthetic package chain, stubs futil
    (the server only calls log/handle_error), and aliases the ALREADY-LOADED canonical
    ``mcpServer.mcp_primitives`` modules into the chain - the SAME module objects, so
    ``isinstance(item, Item)`` checks inside the server hold for Items built by tool modules.
    Idempotent: returns the cached module on repeat calls. Loads under ``_no_bytecode()``, like
    load_tool - the server modules are spec-loaded repo source too.
    """
    full_name = f"{_SERVER_PKG_ROOT}.commands.mcpServer.server.mcp_server"
    if full_name in sys.modules:
        return sys.modules[full_name]

    with _no_bytecode():
        install_mock_adsk()
        if COMMANDS_DIR not in sys.path:
            sys.path.insert(0, COMMANDS_DIR)
        importlib.import_module("mcpServer.mcp_primitives")

        def _pkg(name):
            mod = types.ModuleType(name)
            mod.__path__ = []
            sys.modules[name] = mod
            return mod

        _pkg(_SERVER_PKG_ROOT)
        lib_pkg = _pkg(f"{_SERVER_PKG_ROOT}.lib")
        futil_stub = types.ModuleType(f"{_SERVER_PKG_ROOT}.lib.fusion360utils")
        futil_stub.log = lambda *a, **k: None
        futil_stub.handle_error = lambda *a, **k: None
        lib_pkg.fusion360utils = futil_stub
        sys.modules[futil_stub.__name__] = futil_stub
        _pkg(f"{_SERVER_PKG_ROOT}.commands")
        _pkg(f"{_SERVER_PKG_ROOT}.commands.mcpServer")
        _pkg(f"{_SERVER_PKG_ROOT}.commands.mcpServer.server")

        for suffix in ("", ".item", ".tool", ".annotations", ".registry"):
            src = "mcpServer.mcp_primitives" + suffix
            importlib.import_module(src)
            sys.modules[f"{_SERVER_PKG_ROOT}.commands.mcpServer.mcp_primitives{suffix}"] = \
                sys.modules[src]
        importlib.import_module("mcpServer.version")
        sys.modules[f"{_SERVER_PKG_ROOT}.commands.mcpServer.version"] = sys.modules["mcpServer.version"]

        server_dir = os.path.join(COMMANDS_DIR, "mcpServer", "server")
        for mod_name in ("task_manager", "mcp_server"):
            fq = f"{_SERVER_PKG_ROOT}.commands.mcpServer.server.{mod_name}"
            spec = importlib.util.spec_from_file_location(
                fq, os.path.join(server_dir, f"{mod_name}.py"))
            module = importlib.util.module_from_spec(spec)
            sys.modules[fq] = module
            spec.loader.exec_module(module)
    return sys.modules[full_name]


# Pristine seam per tool module, captured ONCE the first time the module is seen — before any test
# patches it — so the autouse fixture can restore to it.
#
# A tool module reads the active design through one of a few module-level "seam" names: `app`
# (read by _common.design()), the imported-by-value `design`/`target_component`/`_design` helpers it
# calls bare, or `_data` (data tools). A test patches these on its OWN module object (e.g.
# `fl.target_component = lambda x: comp`, `mo.app = ...`). Because load_tool returns ONE canonical
# module object per tool for the whole session, such a patch LEAKS into the next test that uses the
# same module unless restored — producing order-dependent failures (the handler builds onto a stale
# fake). So the fixture restores these seam attrs on EVERY loaded tool module after each test, not
# just the substrate few. (`_design` covers the tools that bind a local `_design`.)
_PRISTINE_SEAMS = {}
_SEAM_ATTRS = ("design", "target_component", "_design", "app", "_data")


def _loaded_tool_modules():
    """Every currently-loaded `mcpServer.tools.*` module object (substrate + tools)."""
    return {name: mod for name, mod in sys.modules.items()
            if name.startswith("mcpServer.tools.") and mod is not None}


def _pristine_seam(key, mod):
    if key not in _PRISTINE_SEAMS:
        _PRISTINE_SEAMS[key] = {a: getattr(mod, a) for a in _SEAM_ATTRS if hasattr(mod, a)}
    return _PRISTINE_SEAMS[key]


def _capture_pristine_seams():
    """Record the as-imported seam values of every loaded tool module that has none recorded yet.

    Called from load_tool the moment a module is executed, and again at each test's SETUP. The
    load-time call is what makes the recording pristine: a module first imported inside a test BODY
    is already past that setup sweep, so without it the module's first recording happens at
    TEARDOWN - and a body that patched a seam imperatively (``mod.app = fake``) has the PATCHED
    value recorded as pristine and restored into the module for every test that follows."""
    for name, mod in _loaded_tool_modules().items():
        _pristine_seam(name, mod)


# Install mocks at collection time, before any test module imports a tool.
install_mock_adsk()


# Pristine snapshot of each adsk mock module's attribute namespace, captured ONCE right after install
# (before any test patches it). Tests routinely assign fake TYPE CLASSES and enum values onto these
# shared mocks — e.g. `adsk.fusion.BRepBody = SomeClass`, `adsk.fusion.MeshBody = ...`,
# `adsk.fusion.DesignTypes.ParametricDesignType = 1`, `adsk.core.Point3D.create = ...`. Because the
# mock modules are shared for the whole session, those assignments LEAK into later tests unless undone
# (a later test then isinstance-checks against the wrong class, or reads a stale enum, and fails only
# in certain orderings). Restoring each module's __dict__ to this snapshot after every test removes
# test-added attributes and reverts changed ones, making the suite order-independent.
def _snapshot_adsk_dicts():
    snap = {}
    for name in ("adsk.core", "adsk.fusion", "adsk.cam"):
        mod = sys.modules[name]
        # Shallow copy of the module-mock's own attribute dict, plus a shallow copy of each child
        # Mock's __dict__ one level down (that's where Type.cast / Type.create / Enum.MEMBER live).
        children = {}
        for attr, child in list(vars(mod).items()):
            cd = getattr(child, "__dict__", None)
            if isinstance(cd, dict):
                children[attr] = dict(cd)
        snap[name] = (dict(vars(mod)), children)
    return snap


def _restore_adsk_dicts(snap):
    for name, (top, children) in snap.items():
        mod = sys.modules[name]
        md = vars(mod)
        md.clear()
        md.update(top)
        for attr, cd in children.items():
            child = md.get(attr)
            chd = getattr(child, "__dict__", None)
            if isinstance(chd, dict):
                chd.clear()
                chd.update(cd)


_PRISTINE_ADSK = _snapshot_adsk_dicts()


@pytest.fixture(autouse=True)
def _restore_shared_adsk_mocks():
    """Snapshot-and-restore the mutable ``adsk`` mock attributes around every test.

    Tool tests install per-test behaviour by REASSIGNING attributes on the shared
    mocks — a cast/create callable (``adsk.fusion.Design.cast``,
    ``adsk.core.ValueInput.createByReal``), a fake type class
    (``adsk.fusion.BRepBody``), an enum member (``DesignTypes.*``). Because these
    live on module-level Mocks shared by the whole session, a reassignment would
    otherwise LEAK into later tests (e.g. a clobbered ``Design.cast`` pass-through
    makes an unrelated tool see no design at all). This autouse fixture records
    the originals before each test and puts them back after, keeping tests
    order-independent without per-file teardown.
    """
    # The whole adsk.core/fusion/cam mock namespace is snapshot/restored from _PRISTINE_ADSK (captured
    # once at install): test-assigned attributes are removed, reassigned ones reverted.
    # Tools that share _common.design()/target_component()/app (instead of a local _design()) are
    # tested by patching those on the _common module (the seam _inputs.py uses). Snapshot them at SETUP
    # and restore after, so a test's patch can't leak into a later test. _common is loaded lazily by
    # load_tool, so it may not exist yet on the very first tests — guard for that.
    # Capture pristine substrate seams at SETUP (before the test body patches them) - the backstop
    # under load_tool's own load-time capture, for a module that reached sys.modules another way.
    _capture_pristine_seams()
    # A few tests stub a tool's filesystem check by assigning `mod.os.path.isfile = lambda …`. Because
    # `mod.os` is the REAL os module, that mutates process-wide os.path and would leak into a later test
    # (e.g. a left-behind `isfile -> False` makes an unrelated upload report "file not found"). Snapshot
    # the real os.path predicates and restore them after the test.
    import os.path as _ospath
    _os_saved = [(_ospath, a, getattr(_ospath, a)) for a in ("isfile", "isdir", "exists")
                 if hasattr(_ospath, a)]
    # The registry SINGLETON is process-global, and several suite-wide tests populate it (a naming
    # lint's per-module reset+register loop, the wire-shape tests' full registration). Since
    # workspace_orient's pointer filter reads the live registry at call time, a leaked PARTIAL
    # registry makes pointer tests order-dependent. Snapshot the singleton pointer AND the instance's
    # tool dict at setup; restore both after - mirroring gen_manifest.collect()'s own guard.
    _reg_mod = sys.modules.get("mcpServer.mcp_primitives.registry")
    _reg_inst = _reg_mod._registry_instance if _reg_mod else None
    _reg_tools = dict(_reg_inst._tools) if _reg_inst is not None else None
    try:
        yield
    finally:
        if _reg_mod is not None:
            _reg_mod._registry_instance = _reg_inst
            if _reg_inst is not None:
                _reg_inst._tools.clear()
                _reg_inst._tools.update(_reg_tools)
        for _obj, _attr, _orig in _os_saved:
            setattr(_obj, _attr, _orig)
        _restore_adsk_dicts(_PRISTINE_ADSK)
        # load_tool returns ONE canonical object per tool module for the whole session, so a test that
        # patches a module-level seam (app/design/target_component/_design/_data) leaks into the next
        # test using that same module. Restore every loaded tool module's seam attrs to PRISTINE
        # (captured the first time the module is seen, before any patch — a per-test snapshot would
        # chain a prior test's patch forward and lose the original). This keeps the suite
        # order-independent without per-file teardown.
        for _name, _mod in _loaded_tool_modules().items():
            for attr, val in _pristine_seam(_name, _mod).items():
                setattr(_mod, attr, val)


# ── small Fusion-shaped fakes a tool's logic branches on ───────────────────
#
# These mimic the *interface* a tool reads, not the whole API. Names match the
# Fusion type names because tools branch on ``type(entity).__name__``.

class FakePoint:
    def __init__(self, x=0.0, y=0.0, z=0.0):
        self.x, self.y, self.z = x, y, z

    def vectorTo(self, other):
        # Mirrors adsk.core.Point3D.vectorTo -> Vector3D(other - self).
        return FakeVector3D(other.x - self.x, other.y - self.y, other.z - self.z)

    def distanceTo(self, other):
        # Mirrors adsk.core.Point3D.distanceTo -> Euclidean distance.
        return ((self.x - other.x) ** 2 + (self.y - other.y) ** 2
                + (self.z - other.z) ** 2) ** 0.5

    def copy(self):
        # Mirrors adsk.core.Point3D.copy -> an independent point at the same coordinates. A world
        # lift copies a surface's own origin BEFORE transforming it, so the surface keeps its
        # untouched reading (_joints._world_torus_centre). type(self), not FakePoint: a subclass
        # modelling a platform that DECLINES the transform must survive that copy.
        return type(self)(self.x, self.y, self.z)

    def transformBy(self, m):
        """Move this point by `m` (a FakeMatrix3D) IN PLACE, answering the bool a caller gates
        on (model_hole._sketch_space_point treats a falsy answer as 'not expressible'). A POINT
        takes the matrix's rotation AND its translation - the live point/vector split
        FakeMatrix3D's two applies keep. Subclass and return False for the platform DECLINING the
        transform."""
        self.x, self.y, self.z = m._apply_point(self.x, self.y, self.z)
        return True


class FakeBoundingBox3D:
    def __init__(self, min_pt, max_pt):
        self.minPoint = min_pt
        self.maxPoint = max_pt


class BRepBody:
    """Matches type(entity).__name__ == 'BRepBody' in the tool's logic. volume/is_solid/entity_token
    are optional (all real BRepBody attributes per live_api_facts.SHAPES) for a before/after
    read-back check (e.g. a cut's volume delta). Visibility mirrors the live contract:
    isLightBulbOn is the body's OWN settable browser bulb; isVisible is the EFFECTIVE state
    (own bulb AND every ancestor's, modeled by hidden_by_ancestor) and has no setter. `vertices`
    takes FakePoints and wraps each as a BRepVertex-shaped item exposing .geometry.

    This is a NATIVE body: nativeObject reads None and assemblyContext reads None, the pair a live
    component-owned body answers. Its occurrence proxy is ``body_proxy(this)``."""
    def __init__(self, name="Body", bbox=None, volume=0.0, is_solid=True, entity_token=None,
                 light_bulb=True, hidden_by_ancestor=False, vertices=(), parent_component=None,
                 face_count=0):
        self.name = name
        self.parentComponent = parent_component
        self.nativeObject = None
        self.assemblyContext = None
        self.boundingBox = bbox
        self.vertices = _NamedCollection([_Vertex(p) for p in vertices])
        self.faces = _NamedCollection([None] * face_count)
        self.volume = volume
        self.isSolid = is_solid
        self.entityToken = entity_token or name
        self.isLightBulbOn = light_bulb
        self._hidden_by_ancestor = hidden_by_ancestor

    @property
    def isVisible(self):
        return bool(self.isLightBulbOn) and not self._hidden_by_ancestor


class _FakeTriangleMesh:
    """MeshBody.displayMesh - the triangle/vertex census a mesh feature is judged on. Held as ONE
    object per body so a feature fake can mutate the counts in place the way a real repair does."""
    def __init__(self, tri, nodes):
        self.triangleCount = tri
        self.nodeCount = nodes


class _FakePolygonMesh:
    """MeshBody.mesh - the flat x,y,z node coordinates a smooth moves and the flat normal
    components a reverse negates."""
    def __init__(self, coords, normals):
        self.nodeCoordinatesAsDouble = list(coords)
        self.normalVectorsAsDouble = list(normals)


class MeshBody:
    """Matches type(entity).__name__ == 'MeshBody' - the shared mesh fake every mesh-feature tool
    test builds on (repair, shell, smooth, separate, reverse_normal).

    `volume` on a mesh that is NOT closed RETURNS 0.0 rather than raising - that reading comes from
    live_api_facts.BEHAVIOR["meshbody_volume_open_raises"], so the platform fact lives in one place
    and a change to it flips every mesh test at once. An open mesh encloses nothing, so the 0.0 is
    the API's ANSWER: it is comparable at both ends of a repair, it carries no sign for a reverse to
    flip, and it makes a percentage undefined for a smooth.

    `isValid` stays True after a feature consumes the body - the measured lie - so a handler that
    trusts it instead of a fresh collection walk cannot pass on that flag; ``go_stale`` drops the
    identity reads a consumed body no longer answers.

    Every harness knob is PRIVATE, so the public surface is only what a live MeshBody answers and
    test_fake_shapes_exist sweeps it against the measured dump. The readability switches model the
    reads that fail INDEPENDENTLY, each one making exactly one published field null: `_dead` (an
    invalidated wrapper - every read raises), `_counts_readable` (displayMesh), `_volume_readable`,
    `_closed_readable`, `_mesh_readable` (the PolygonMesh behind both the coordinates and the
    normals). A test flips one on the instance to break that read mid-flight."""
    def __init__(self, name="Scan1", tri=12, nodes=8, is_closed=True, volume=1.0, coords=(),
                 normals=(), token=None, parent=None, counts_readable=True, volume_readable=True,
                 closed_readable=True, mesh_readable=True):
        self.name = name
        self.isValid = True
        self._dead = False
        self._display = _FakeTriangleMesh(tri, nodes)
        self._is_closed = is_closed
        self._volume_cm3 = volume
        self._coords = list(coords)
        self._normals = list(normals)
        self._counts_readable = counts_readable
        self._volume_readable = volume_readable
        self._closed_readable = closed_readable
        self._mesh_readable = mesh_readable
        self.entityToken = token or f"MTOK::{name}"
        self.parentComponent = parent

    def _live(self):
        if self._dead:
            raise RuntimeError("3 : object is no longer valid")

    @property
    def displayMesh(self):
        self._live()
        if not self._counts_readable:
            raise RuntimeError("3 : the display mesh is unavailable")
        return self._display

    @property
    def mesh(self):
        self._live()
        if not self._mesh_readable:
            raise RuntimeError("3 : the polygon mesh is unavailable")
        return _FakePolygonMesh(self._coords, self._normals)

    @property
    def isClosed(self):
        self._live()
        if not self._closed_readable:
            raise RuntimeError("3 : the watertight flag of this body is unavailable")
        return self._is_closed

    @isClosed.setter
    def isClosed(self, value):
        self._is_closed = value

    @property
    def isOriented(self):
        self._live()
        return True

    @property
    def volume(self):
        self._live()
        if not self._volume_readable:
            raise RuntimeError("3 : the volume of this body is unavailable")
        if self._is_closed:
            return self._volume_cm3
        if _api_facts.BEHAVIOR["meshbody_volume_open_raises"]:
            raise RuntimeError("3 : the volume of this body is unavailable")
        return 0.0


class _EntityProxy:
    """See ``entity_proxy``. Deliberately holds no state of its own - reads and writes both go to the
    one underlying entity, so only object IDENTITY differs."""

    def __init__(self, obj):
        object.__setattr__(self, "_obj", obj)

    def __getattr__(self, name):
        return getattr(object.__getattribute__(self, "_obj"), name)

    def __setattr__(self, name, value):
        setattr(object.__getattribute__(self, "_obj"), name, value)

    def __delattr__(self, name):
        delattr(object.__getattribute__(self, "_obj"), name)


def entity_proxy(obj):
    """A DISTINCT Python object standing for the same entity - what Fusion hands back on every read.

    LIVE-MEASURED, and it is not confined to bodies:
      * three faces of one box, and three edges of one open surface body, each gave N distinct python
        ids and ONE entityToken (``f0.body is f1.body`` False);
      * two reads of ``design.rootComponent`` return DIFFERENT objects, as do rootComponent vs
        ``body.parentComponent`` vs ``edge.body.parentComponent`` - all four sharing one entityToken.

    So identity NEVER carries an is-it-the-same test, for bodies or components alike. Every read
    delegates to `obj`, so a mutation a fake applies is visible through each proxy. Hand one out per
    reference whenever a test covers code that compares or dedupes entities: reusing the SAME object
    makes an identity-keyed comparison indistinguishable from a token-keyed one, which is exactly how
    that class of defect survives a green suite. A harness affordance, deliberately NOT a method on
    the fakes - they expose only attributes the live types have.
    """
    return _EntityProxy(obj)


class _OccurrenceProxy(_EntityProxy):
    """See ``body_proxy``. Every read but the three that make a proxy a proxy goes to the native."""

    def __init__(self, native, occurrence=None, entity_token=None):
        _EntityProxy.__init__(self, native)          # explicit: zero-arg super() and __class__ clash
        # One token PER PLACEMENT: a proxy's token addresses a body IN one occurrence (a handle for
        # instance 2 must not resolve to instance 1), so two placements' proxies read distinct
        # tokens live - the fake folds the occurrence into the default for the same reason.
        token = entity_token or (f"PROXY::{getattr(occurrence, 'name', None)}"
                                 f"::{getattr(native, 'entityToken', None)}")
        object.__setattr__(self, "_token", token)
        object.__setattr__(self, "_occurrence", occurrence)

    @property
    def __class__(self):
        # A proxy IS a BRepBody live, and body code isinstance-checks against adsk.fusion.BRepBody.
        # isinstance consults __class__, so the proxy answers the wrapped fake's type.
        return type(object.__getattribute__(self, "_obj"))

    @property
    def entityToken(self):
        return object.__getattribute__(self, "_token")

    @property
    def nativeObject(self):
        return object.__getattribute__(self, "_obj")

    @property
    def assemblyContext(self):
        return object.__getattribute__(self, "_occurrence")


def body_proxy(native, occurrence=None, entity_token=None):
    """The occurrence PROXY of `native` - what an occurrence's bRepBodies hands back for a body its
    component owns natively.

    LIVE-MEASURED, and the reason a token cannot be the de-dup key on its own: a proxy's entityToken
    DIFFERS from its native's (each is stable across re-fetches of that wrapper), while
    ``proxy.nativeObject`` IS the native and a native's own ``nativeObject`` reads None. One physical
    body therefore answers two tokens, and a walk that reaches it both natively and through an
    occurrence sees two entities unless it keys on ``(nativeObject or self).entityToken``. `occurrence`
    is the Occurrence the proxy hangs off (its fullPathName is the body's context); every other read
    and write delegates to `native`, so a mutation is visible through both.
    """
    return _OccurrenceProxy(native, occurrence, entity_token)


class _NamedCollection:
    """Counted collection (Fusion's count/item(i)) with itemByName lookup (None on a miss),
    iterable - the measured live protocol (see live_api_facts; NamedViews' raise-on-miss is the
    known exception, see test_view_set)."""
    def __init__(self, items=()):
        self._items = list(items)

    @property
    def count(self):
        return len(self._items)

    def item(self, i):
        if 0 <= i < len(self._items):
            return self._items[i]
        if _api_facts.BEHAVIOR["collection_item_out_of_range_raises"]:
            # live, the raise can escape try/except entirely - bound-check against .count
            raise RuntimeError("3 : invalid argument index")
        return None

    def itemByName(self, name):
        for it in self._items:
            if getattr(it, "name", None) == name:
                return it
        return None

    def __iter__(self):
        return iter(self._items)


def make_bbox(minp, maxp):
    """A FakeBoundingBox3D from (min xyz, max xyz) tuples in cm (Fusion's internal unit). The plain
    function, so a module-level fake that HOLDS a bounding box can build one without a fixture."""
    return FakeBoundingBox3D(FakePoint(*minp), FakePoint(*maxp))


@pytest.fixture
def bbox():
    """Factory: FakeBoundingBox3D from (min xyz, max xyz) in cm (Fusion's unit)."""
    return make_bbox


# ── vectors / surfaces / curves for selection.py classification ────────────
#
# selection.py branches on type(surface).__name__ ("Plane", "Cylinder", ...)
# and type(curve).__name__ ("Line3D", "Circle3D", ...), so the geometry fakes
# below are NAMED to match those runtime type names exactly.

class FakeVector3D:
    """Vector matching Fusion's real Vector3D interface: plain .x/.y/.z plus .length/.copy()/
    .normalize().

    Zero-vector behavior is the measured BEHAVIOR flag: live normalize() reports success and
    leaves the components untouched, so callers zero-check by magnitude, never by the return
    value.
    """
    def __init__(self, x=0.0, y=0.0, z=0.0):
        self.x, self.y, self.z = x, y, z

    @property
    def length(self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5

    def copy(self):
        # type(self), not FakeVector3D: a subclass modelling ONE refusing axis must survive the
        # copy a lift takes before transforming (_assembly_detail._world_axes copies, then transforms).
        return type(self)(self.x, self.y, self.z)

    def normalize(self):
        mag = (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
        if mag < 1e-12:
            return bool(_api_facts.BEHAVIOR["vector3d_normalize_true_on_zero"])
        self.x, self.y, self.z = self.x / mag, self.y / mag, self.z / mag
        return True

    def dotProduct(self, other):
        # Mirrors adsk.core.Vector3D.dotProduct.
        return self.x * other.x + self.y * other.y + self.z * other.z

    def isParallelTo(self, other):
        # Mirrors adsk.core.Vector3D.isParallelTo: parallel regardless of sense (cross ~ 0).
        cx = self.y * other.z - self.z * other.y
        cy = self.z * other.x - self.x * other.z
        cz = self.x * other.y - self.y * other.x
        return (cx * cx + cy * cy + cz * cz) ** 0.5 < 1e-9

    def transformBy(self, m):
        """Move this DIRECTION by `m` (a FakeMatrix3D) IN PLACE, answering the bool a caller gates
        on. A vector takes the matrix's ROTATION ONLY, so a placement's translation can never reach
        an axis through it - the same live split FakePoint.transformBy sits on the other side of.
        Subclass and return False for one axis the platform declines to express."""
        self.x, self.y, self.z = m._apply_vector(self.x, self.y, self.z)
        return True


class FakeMatrix3D:
    """Numeric adsk.core.Matrix3D: a rotation of `deg` about Z followed by a translation `t` (cm).

    Its PUBLIC surface is the pair a world lift calls on the matrix itself - ``copy()`` and
    ``invert()``, which inverts IN PLACE and answers a bool the way Matrix3D.invert does; pass
    ``invertible=False`` for the platform DECLINING the inversion - the False every production
    caller gates on (model_inspect._measuring_axes, model_hole._world_lift). Measured: a SINGULAR
    matrix does not produce that False - invert() answers True and corrupts the matrix to nan/inf
    (ledger row matrix3d-invert-singular-answers-true-and-corrupts); rigid occurrence transforms
    cannot be singular, so the gate is defensive. The rotation/translation state and the arithmetic
    below it are underscored because they are this fake's own plumbing to a fake Point3D/Vector3D,
    not members of the type it impersonates - a fake that published them would teach tool code an
    API Fusion has no equivalent of.

    That arithmetic keeps the POINT/VECTOR split the live API makes: Point3D.transformBy takes the
    translation, Vector3D.transformBy does not. So a fake point calls ``_apply_point`` and a fake
    DIRECTION calls ``_apply_vector``, and a lift that leaked a placement's translation into an axis
    reads wrong here instead of passing.

    A ROTATED placement is what tells a real lift apart from a backwards one - under identity the
    two are the same matrix.
    """
    def __init__(self, deg=0.0, t=(0.0, 0.0, 0.0), invertible=True):
        self._deg = float(deg)
        self._t = tuple(float(v) for v in t)
        self._invertible = bool(invertible)

    def copy(self):
        return type(self)(self._deg, self._t, self._invertible)

    def invert(self):
        if not self._invertible:
            return False
        # (R, t) -> (R^-1, -R^-1 t)
        r = math.radians(-self._deg)
        c, s = math.cos(r), math.sin(r)
        tx, ty, tz = self._t
        self._deg = -self._deg
        self._t = (-(c * tx - s * ty), -(s * tx + c * ty), -tz)
        return True

    def _apply_vector(self, x, y, z):
        """The rotation ONLY - what a Vector3D gets, so a direction never picks up a placement."""
        r = math.radians(self._deg)
        c, s = math.cos(r), math.sin(r)
        return (c * x - s * y, s * x + c * y, z)

    def _apply_point(self, x, y, z):
        """The rotation AND the translation - what a Point3D gets."""
        vx, vy, vz = self._apply_vector(x, y, z)
        return (vx + self._t[0], vy + self._t[1], vz + self._t[2])


class FakeInfiniteLine3D:
    """Numeric adsk.core.InfiniteLine3D: origin + direction, with the colinearity test the holder
    profile reduction runs (parallel directions AND the origin offset lying along the direction)."""
    def __init__(self, origin, direction):
        self.origin = origin
        self.direction = direction

    @staticmethod
    def create(origin, direction):
        return FakeInfiniteLine3D(origin, direction)

    def isColinearTo(self, other):
        if not self.direction.isParallelTo(other.direction):
            return False
        off = self.origin.vectorTo(other.origin)
        return off.length < 1e-9 or off.isParallelTo(self.direction)


class Plane:
    """surfaceType is intrinsic (a Plane fake IS always PlaneSurfaceType) - set automatically so
    callers reading face.geometry.surfaceType don't each hand-wire the same measured constant.
    create/intersectWithLine mirror the adsk.core.Plane geometry the holder reduction leans on."""
    def __init__(self, normal, origin=None):
        self.normal = normal
        self.origin = origin
        self.surfaceType = _api_facts.ENUMS["core.SurfaceTypes"]["PlaneSurfaceType"]

    @staticmethod
    def create(origin, normal):
        return Plane(normal, origin)

    def intersectWithLine(self, line):
        # Mirrors adsk.core.Plane.intersectWithLine: None for a line parallel to the plane.
        denom = self.normal.dotProduct(line.direction)
        if abs(denom) < 1e-12:
            return None
        t = self.normal.dotProduct(line.origin.vectorTo(self.origin)) / denom
        return FakePoint(line.origin.x + t * line.direction.x,
                         line.origin.y + t * line.direction.y,
                         line.origin.z + t * line.direction.z)


class Cylinder:
    """surfaceType is intrinsic - see Plane."""
    def __init__(self, axis, origin=None):
        self.axis = axis
        self.origin = origin
        self.surfaceType = _api_facts.ENUMS["core.SurfaceTypes"]["CylinderSurfaceType"]


class Cone:
    """A conical surface - mirrors Cylinder's .axis (both expose it per the live _inputs.py
    face-axis code). surfaceType is intrinsic - see Plane."""
    def __init__(self, axis, origin=None):
        self.axis = axis
        self.origin = origin
        self.surfaceType = _api_facts.ENUMS["core.SurfaceTypes"]["ConeSurfaceType"]


class Sphere:
    pass


class Torus:
    """A toroidal surface - surfaceType is intrinsic, see Plane. `origin` is the torus CENTRE, the
    point the torus keypoint gate lifts into world and compares a JointGeometry against: MEASURED
    (shape-dump-torus) - a torus created centred at (2, 3, -1) reads that point back, and the
    surface's own origin reads unchanged after a transform of a COPY of it."""
    def __init__(self, origin=None):
        self.origin = origin
        self.surfaceType = _api_facts.ENUMS["core.SurfaceTypes"]["TorusSurfaceType"]


class Line3D:
    """curveType is intrinsic - see Plane."""
    def __init__(self, start=None, end=None):
        self.startPoint = start
        self.endPoint = end
        self.curveType = _api_facts.ENUMS["core.Curve3DTypes"]["Line3DCurveType"]

    def asInfiniteLine(self):
        # Mirrors adsk.core.Line3D.asInfiniteLine: through startPoint along start->end.
        d = self.startPoint.vectorTo(self.endPoint)
        d.normalize()
        return FakeInfiniteLine3D(self.startPoint, d)


class Circle3D:
    """curveType is intrinsic - see Plane."""
    def __init__(self, normal, center=None, radius=None):
        self.normal = normal
        self.center = center
        self.radius = radius
        self.curveType = _api_facts.ENUMS["core.Curve3DTypes"]["Circle3DCurveType"]


# ── CAM tree fakes (setup / folder / operation) ────────────────────────────
#
# The shared object model for the CAM setup/operation tree every cam_* tool walks. The one
# load-bearing behavior lives here ONCE: allOperations mirrors the measured live flatten
# (BEHAVIOR flags) - folder/pattern children are flattened IN while the folder/pattern
# CONTAINERS are DROPPED - so a container is only reachable through the explicit
# .operations/.folders/.patterns walk, exactly like live Fusion.

class FakeOperation:
    """A CAM Operation leaf. Every attribute is real per live_api_facts.SHAPES['Operation'].

    state_readable=False models an operationState whose READ raises (the _InspPoint shape): the one
    lifecycle member that answers nothing while the flags beside it read normally. Callers
    read it through safe() with no default, so the facts carry operation_state None - every value
    operationState CAN answer is itself a state, so a coerced default would publish one of them off
    a read that never happened."""
    def __init__(self, name, has_toolpath=True, valid=True, suppressed=False, shown=False,
                 operation_state=0, has_error=False, error="", has_warning=False, warning="",
                 state_readable=True):
        self.name = name
        self.hasToolpath = has_toolpath
        self.isToolpathValid = valid
        self.isSuppressed = suppressed
        self.isLightBulbOn = shown
        self.hasError = has_error
        self.error = error
        self.hasWarning = has_warning
        self.warning = warning
        self.isGenerating = False
        self.generatingProgress = None
        self._operation_state = operation_state
        self._state_readable = state_readable

    @property
    def operationState(self):
        if not self._state_readable:
            raise RuntimeError("operationState cannot be read on this operation")
        return self._operation_state


class FakeCAMFolder:
    """A CAM folder/pattern container: .operations/.folders/.patterns hold the DIRECT children
    (Fusion's count/item protocol); allOperations applies the measured flatten (see the section
    note above). Use it for a pattern too - the tools classify nodes STRUCTURALLY (by which
    collection yielded them), never by type name."""
    def __init__(self, name, ops=(), folders=(), patterns=()):
        self.name = name
        self.operations = _NamedCollection(list(ops))
        self.folders = _NamedCollection(list(folders))
        self.patterns = _NamedCollection(list(patterns))

    @property
    def allOperations(self):
        flat = list(self.operations)
        for coll in (self.folders, self.patterns):
            for child in coll:
                if _api_facts.BEHAVIOR["alloperations_flattens_folder_children"]:
                    flat.extend(child.allOperations)
                if not _api_facts.BEHAVIOR["alloperations_drops_folder_objects"]:
                    flat.append(child)
        return _NamedCollection(flat)


class FakeSetup(FakeCAMFolder):
    """A CAM Setup: the same container protocol + measured allOperations flatten as FakeCAMFolder,
    plus Setup.parameters - the collection the WCS binding is written to and read back from
    (build one with wcs_params below; None models a setup whose parameters do not read) - and the
    activate()/isActive pair. activate() returns a bool AND flips isActive, as the live one does;
    'activate_lies' models it returning true while the setup never becomes active."""

    def __init__(self, name, ops=(), folders=(), patterns=(), parameters=None, is_active=False,
                 activate_ok=True, activate_lies=False):
        super().__init__(name, ops=ops, folders=folders, patterns=patterns)
        self.parameters = parameters
        self.isActive = is_active
        self._activate_ok = activate_ok
        self._activate_lies = activate_lies
        self._activate_calls = 0     # bookkeeping, private: the live Setup has no such member

    def activate(self):
        self._activate_calls += 1
        if self._activate_ok and not self._activate_lies:
            self.isActive = True
        return self._activate_ok


# Setup.parameters as the WCS read-back sees it. Named without a Fake prefix because CAMParameter
# has no live SHAPES dump to sweep against (test_fake_shapes_exist), like the _Insp* trio below.

class _SetupParam:
    """A CAMParameter: .name plus .value, whose OWN .value is the payload - the mode string on a
    ChoiceParameterValue, the iterable of bound entities on a CadObjectParameterValue."""

    def __init__(self, name, value):
        self.name = name
        self.value = types.SimpleNamespace(value=value)


def wcs_params(origin_mode=None, orientation_mode=None, origin=None, z_axis=None):
    """A Setup.parameters collection holding the WCS parameters. A mode is its string; `origin` /
    `z_axis` are lists of (object_type, name) entity specs - None omits that parameter entirely,
    [] models a present-but-unbound one, and name=None models an entity with no readable name."""
    def _entity(spec):
        object_type, name = spec
        ent = types.SimpleNamespace(objectType=object_type)
        if name is not None:
            ent.name = name
        return ent

    params = []
    for pname, mode in (("wcs_origin_mode", origin_mode),
                        ("wcs_orientation_mode", orientation_mode)):
        if mode is not None:
            params.append(_SetupParam(pname, mode))
    for pname, specs in (("wcs_origin_point", origin), ("wcs_orientation_axisZ", z_axis)):
        if specs is not None:
            params.append(_SetupParam(pname, [_entity(s) for s in specs]))
    return _NamedCollection(params)


def make_cam(*setups):
    """A minimal CAM product carrying `setups` (count/item protocol) - pair with
    `monkeypatch.setattr(mod, "get_cam", lambda: (cam, None))`."""
    return types.SimpleNamespace(setups=_NamedCollection(list(setups)))


# ── inspection results (CAM.inspectionResults) - the recorded probing measurements ────────────────
#
# The member sets are exactly the live ones. _InspMeasure has NO .name on purpose: a measure folder
# exposes none (the browser name is not readable, and no call enumerates the legal names), so a fake
# that carried one would teach a round-trip that cannot exist. Named without a Fake prefix because
# these types have no live SHAPES dump to sweep against (test_fake_shapes_exist).

class _InspPoint:
    """InspectionPointResult: nominalPosition/projectedPoint/contact (Point3D), delta (Vector3D),
    offset/deviation/error (CM) and state. readable=False models a property that raises."""

    def __init__(self, state, deviation=0.0, error=0.0, offset=0.0, nominal=(0.0, 0.0, 0.0),
                 contact=(0.0, 0.0, 0.0), projected=(0.0, 0.0, 0.0), delta=(0.0, 0.0, 0.0),
                 readable=True):
        self.state = state
        self._deviation = deviation
        self.error = error
        self.offset = offset
        self.nominalPosition = FakePoint(*nominal)
        self.contact = FakePoint(*contact)
        self.projectedPoint = FakePoint(*projected)
        self.delta = FakeVector3D(*delta)
        self._readable = readable

    @property
    def deviation(self):
        if not self._readable:
            raise RuntimeError("deviation cannot be read on this point")
        return self._deviation


class _InspPath:
    """InspectionPathResult: pointResults is its only member (a counted collection; the shared
    _NamedCollection's itemByName goes unused - the live one carries only count/item)."""

    def __init__(self, points):
        self.pointResults = _NamedCollection(list(points))


class _InspMeasure:
    """CAMMeasure: inspectionPathResults is its only member. paths=None models the documented
    'null if none found'."""

    def __init__(self, paths):
        self.inspectionPathResults = None if paths is None else _NamedCollection(list(paths))


def make_inspection_cam(measures):
    """A CAM product whose inspectionResults is a collection of `measures`. measures=None models the
    MEASURED empty state: the property reads None on a document that has never been probed."""
    return types.SimpleNamespace(
        inspectionResults=None if measures is None else _NamedCollection(list(measures)))


def make_gated_cam(member="inspectionResults", text="preview feature is not enabled"):
    """A CAM product whose `member` RAISES on read - the gated-member shape (measured on
    stockMaterialLibrary), which is a different answer from the property reading None."""
    def _raise(self):
        raise RuntimeError(text)
    return type("_GatedCam", (), {member: property(_raise)})()


class FakeUnitsManager:
    """A UnitsManager whose evaluateExpression resolves only a known set - an unknown reference
    RAISES, matching the live FusionUnitsManager (it errors on an unresolvable or dimension-
    incompatible expression). The shared engine for a tool that accepts a parameter-EXPRESSION
    string routed through ValueInput.createByString (model_extrude's distance, model_construction's
    offset). model_extrude.py still keeps a local copy pending migration to this one.

    A resolvable expression evaluates to `value`, and the `units` argument acts the four measured
    live ways - which is what lets a caller tell the shapes apart:
      arithmetic (the default)   scales with the argument      '5'   -> 5.0 "", 0.5 "mm", 0.0873 "deg"
      `dimensioned` names        carries its own unit          '5 mm'-> 0.5 under "" and "mm"
      `angle_dimensioned` names  carries its own ANGULAR unit  30 deg-> its radian value under "" and
                                                                "deg", RAISES under a length unit
      `strict_unitless` names    RAISES under ANY unit         a bare unitless PARAMETER is readable
                                                                only with no units at all
    `value` sets the number a case needs (e.g. a non-positive one)."""
    defaultLengthUnits = "mm"

    # internal units per display unit - Fusion holds lengths in cm and angles in radians, so a
    # unitless expression read as mm returns a tenth of its plain number and one read as deg returns
    # its radian equivalent.
    _CM_PER_UNIT = {"": 1.0, "mm": 0.1, "cm": 1.0, "in": 2.54,
                    "deg": 0.017453292519943295, "rad": 1.0}

    _ANGLE_UNITS = ("deg", "rad")

    def __init__(self, valid=("25 mm", "StockZ/2"), value=2.5, dimensioned=(), strict_unitless=(),
                 angle_dimensioned=()):
        self._valid = set(valid)
        self._value = value
        self._dimensioned = set(dimensioned)
        self._strict_unitless = set(strict_unitless)
        self._angle_dimensioned = set(angle_dimensioned)

    def evaluateExpression(self, expr, units=None):
        if expr not in self._valid:
            raise RuntimeError(f"unresolved parameter in '{expr}'")
        if expr in self._dimensioned:
            return self._value
        if expr in self._angle_dimensioned:
            if units and units not in self._ANGLE_UNITS:
                raise RuntimeError(f"'{expr}' is not a valid expression in a {units} context")
            return self._value
        if units and expr in self._strict_unitless:
            raise RuntimeError(f"'{expr}' is not a valid expression in a {units} context")
        return self._value * self._CM_PER_UNIT.get(units or "", 1.0)


class _Vertex:
    def __init__(self, point):
        self.geometry = point


class BRepFace:
    """Matches type(entity).__name__ == 'BRepFace'. `geometry` is the surface.

    `_classify` reads area/centroid/edges.count/body.name when it builds a face
    record; supply benign defaults so the result is JSON-serializable. Override
    via kwargs in tests that assert on them. `entity_token` is None by default (matching a fake
    built before handle-minting needed it - safe() degrades a None token the same as a missing
    attribute); set it for a test that mints/asserts on a find_geometry-style handle.

    `body` supplies the owning BRepBody itself (for a volume/token read); `body_name` is the
    lighter name-only stand-in. `normal` installs a surface evaluator whose getNormalAtPoint
    returns it - the live (bool, Vector3D) tuple. Without `normal` the face carries no evaluator,
    which is how a face whose normal cannot be sampled reads. `bounding_box` is the face's own AABB
    (BRepFace.boundingBox); without it the face reads as one whose box is unavailable.
    `assembly_context` is the occurrence a PROXY face was read through - None (the default) is a
    NATIVE face, whose reads are in its owning component's space.
    """
    def __init__(self, surface, area=0.0, centroid=None, edge_count=0, body_name=None,
                 entity_token=None, body=None, point_on_face=None, normal=None,
                 bounding_box=None, assembly_context=None):
        self.geometry = surface
        self.assemblyContext = assembly_context
        if bounding_box is not None:
            self.boundingBox = bounding_box
        self.area = area
        self.centroid = centroid
        self.edges = _NamedCollection([None] * edge_count)
        self.body = body if body is not None else (_SimpleNamed(body_name) if body_name else None)
        self.entityToken = entity_token
        self.pointOnFace = point_on_face
        if normal is not None:
            self.evaluator = types.SimpleNamespace(
                getNormalAtPoint=lambda _pt, n=normal: (True, n))


class _SimpleNamed:
    def __init__(self, name):
        self.name = name


class BRepEdge:
    """Matches type(entity).__name__ == 'BRepEdge'. `geometry` is the curve. `point_on_edge`/
    `entity_token` are None by default (see BRepFace) - set them for a test that mints/asserts on a
    find_geometry-style handle."""
    def __init__(self, curve, start=None, end=None, point_on_edge=None, entity_token=None):
        self.geometry = curve
        self.startVertex = _Vertex(start) if start else None
        self.endVertex = _Vertex(end) if end else None
        self.pointOnEdge = point_on_edge
        self.entityToken = entity_token


# ── shared fake-design builder + dual-seam install (the test-plumbing convention) ───────────────────
#
# A tool reads the active design through TWO seams:
#   • its own  `mod._common.design()` / `target_component()`  (and `mod.app`), and
#   • the input-kinds' `mod._inputs._common.design()` / `target_component()`  (BodyRef/PlaneRef/… use
#     _inputs, which has its OWN bound _common reference).
# Patching only the first is a silent trap: the handler resolves but the INPUT kind resolves against
# the wrong (or stale) design, so the test passes while testing the wrong thing. install() patches
# BOTH seams to the same design, making "patch both seams" structural instead of a remembered rule.

class MakeComp:
    """A component with the standard Fusion collection protocol (count/item/itemByName).

    Pass bodies as names (str) or objects with a `.name`. Extra collections a specific tool needs
    (e.g. a fake `features`) can be attached by the caller after construction, or pass a ready-made
    component to `make_design(comp=...)` instead.
    """
    def __init__(self, name="Root", bodies=(), occurrences=(), sketches=(), entity_token=None,
                 parent_design=None):
        self.name = name
        norm = [b if hasattr(b, "name") else BRepBody(b) for b in bodies]
        self.bRepBodies = _NamedCollection(norm)
        self.occurrences = _NamedCollection(list(occurrences))
        self.allOccurrences = list(occurrences)
        self.sketches = _NamedCollection(list(sketches))
        self.boundingBox = None
        # Set only when asked: a component whose token does NOT read is its own tested state, and
        # every live component has a token but two DISTINCT ones can share it (document-local), so a
        # test that cares about identity must choose the tokens rather than inherit a default.
        if entity_token is not None:
            self.entityToken = entity_token
        # The design this component belongs to - the first hop of the chain a body's SOURCE DOCUMENT
        # is read through (parentComponent -> parentDesign -> parentDocument -> dataFile.id). Set
        # only when asked, so a component whose document cannot be read stays a testable state; see
        # make_source_document.
        if parent_design is not None:
            self.parentDesign = parent_design


class MakeDesign:
    """A design exposing the attributes tools/inputs read: rootComponent, activeComponent (defaults to
    root), allOccurrences, allComponents, and findEntityByToken(token) backed by a `tokens` map.

    `parent_document` is the Document this design belongs to - the second hop of the source-document
    chain (see make_source_document). Set only when asked: a design whose document cannot be read is
    its own tested state, and that is what an unsaved or unreachable document looks like."""
    def __init__(self, comp=None, tokens=None, all_components=None, parent_document=None):
        self.rootComponent = comp if comp is not None else MakeComp()
        self.activeComponent = self.rootComponent
        if parent_document is not None:
            self.parentDocument = parent_document
        self._tokens = dict(tokens or {})
        self._all_components = list(all_components) if all_components is not None else [self.rootComponent]

    @property
    def allComponents(self):
        # A counted+iterable collection on the DESIGN, as in the live API - Component has no
        # allComponents attribute, so a fake must not offer one anywhere else.
        return _NamedCollection(self._all_components)

    def findEntityByToken(self, token):
        # Live returns a SWIG BaseVector, not a list - len/bool/index/iterate behave list-like
        # (live-verified), so never assert isinstance(result, list). A token can answer with SEVERAL
        # entities (measured: splitting a face makes the pre-split token resolve to BOTH
        # survivors), so a tokens entry may be a LIST and is handed back as-is.
        e = self._tokens.get(token)
        if isinstance(e, (list, tuple)):
            return list(e)
        return [e] if e is not None else []


def make_source_document(urn):
    """The `parentDesign` a component in the document with lineage id `urn` answers.

    An entity's SOURCE DOCUMENT is read through parentComponent -> parentDesign -> parentDocument ->
    dataFile.id (``_common.native_identity``), and that id is what separates two entities in two
    x-ref'd documents whose document-local entityTokens collide. Pass ``urn=None`` for a NEVER-SAVED
    document: it carries no dataFile at all, so the chain stops one hop short.

    Hand a DIFFERENT urn to each component standing for a different source document; hand the SAME
    one to components of a single document. Document/DataFile have no measured shape dump, so those
    two hops are attribute bags rather than mapped fakes."""
    return MakeDesign(parent_document=types.SimpleNamespace(
        dataFile=(types.SimpleNamespace(id=urn) if urn is not None else None)))


def make_design(bodies=(), occurrences=(), tokens=None, comp=None, all_components=None,
                sketches=()):
    """Build a standard FakeDesign. Use `comp=` to supply a tool-specific component (one carrying a
    fake `features`/`exportManager`/… surface); otherwise a plain MakeComp(bodies, occurrences)."""
    if comp is None:
        comp = MakeComp(bodies=bodies, occurrences=occurrences, sketches=sketches)
    return MakeDesign(comp=comp, tokens=tokens, all_components=all_components)


class FakeOccurrence:
    """One assembly occurrence: the component it places, its fullPathName, its name.

    ``raises`` models the UNRESOLVED EXTERNAL REFERENCE state, and models it the way it was
    MEASURED: the occurrence is present in the tree and EVERY read on it throws. ``component``
    raising is the only reliable detector (isReferencedComponent / isValid / isLightBulbOn all read
    normally on a real broken reference), and ``fullPathName`` raises too - which is why code that
    names an occurrence in an error must fall back to the string it was handed. A fake that raises
    only on ``component`` lets a missing fullPathName guard survive its own test.

    ``name`` keeps reading in that state: it is the one identity a caller can still publish.

    ``transform2`` is what the occurrence PLACES its component with (a FakeMatrix3D) and
    ``assemblyContext`` the occurrence placing THIS one, or None where the chain ends at the root -
    the pair a placement ladder walks. Both answer through ``raises`` like every other read here:
    that is this fake's declared contract, not a second measurement (the measured detectors named
    above are ``component`` and ``fullPathName``), and holding a new read to it is what stops a
    caller reading a placement off an occurrence whose component will not load.

    ONE class, so a test can point ``adsk.fusion.Occurrence`` at it and the shared occurrence
    resolver's isinstance check passes on a handle it resolved.
    """

    def __init__(self, path="Comp:1", component=None, raises=None, transform2=None,
                 assembly_context=None):
        self._path = path
        self._component = component
        self._raises = raises
        self._transform2 = transform2
        self._assembly_context = assembly_context
        self.name = path.split("+")[-1]

    def _read(self, value):
        if self._raises:
            raise RuntimeError(self._raises)
        return value

    @property
    def fullPathName(self):
        return self._read(self._path)

    @property
    def component(self):
        return self._read(self._component)

    @property
    def transform2(self):
        return self._read(self._transform2)

    @property
    def assemblyContext(self):
        return self._read(self._assembly_context)


def make_occurrence(path="Comp:1", component=None, raises=None, transform2=None,
                    assembly_context=None):
    """An occurrence placing `component` at assembly path `path`, with the placement matrix
    ``transform2`` and the occurrence ``assembly_context`` that places it. Pass ``raises`` to model
    an unresolved external reference, where every read but ``name`` throws that message."""
    return FakeOccurrence(path, component, raises, transform2, assembly_context)


def make_sketch_curve(token="curve0", length=1.0, is_closed=None):
    """One sketch curve: entityToken + length (cm), the pair a curve-edit read-back keys on. Only a
    fitted spline reports isClosed live, so it is set only when given. Attach the in-place edit
    methods a test drives (trim/extend/breakCurve/split) to the returned object."""
    curve = types.SimpleNamespace(entityToken=token, length=length, isConstruction=False)
    if is_closed is not None:
        curve.isClosed = is_closed
    return curve


def make_sketch(name="Sketch1", lines=(), arcs=(), circles=(), ellipses=(), splines=(), points=()):
    """A Sketch fake: sketchCurves (flat, plus the per-kind sub-collections a '<type>:<index>' ref
    indexes), sketchPoints and name. Members come from make_sketch_curve; a collection-level factory
    a test drives (sketchArcs.addFillet, sketchLines.addDistanceChamfer) is attached to the returned
    collection."""
    members = list(lines) + list(arcs) + list(circles) + list(ellipses) + list(splines)
    curves = _NamedCollection(members)
    curves.sketchLines = _NamedCollection(lines)
    curves.sketchArcs = _NamedCollection(arcs)
    curves.sketchCircles = _NamedCollection(circles)
    curves.sketchEllipses = _NamedCollection(ellipses)
    curves.sketchFittedSplines = _NamedCollection(splines)
    curves.sketchControlPointSplines = _NamedCollection()
    curves.sketchFixedSplines = _NamedCollection()
    return types.SimpleNamespace(name=name, sketchCurves=curves,
                                 sketchPoints=_NamedCollection(points))


def sketch_curves_edit(sketch, collection, add=(), remove=()):
    """Apply a curve add/remove to a sketch fake. A sketch curve sits in TWO collections - the flat
    sketchCurves a count read-back walks and the per-kind sub-collection a '<type>:<index>' ref
    indexes - so both are updated together."""
    for curve in remove:
        sketch.sketchCurves._items.remove(curve)
        collection._items.remove(curve)
    for curve in add:
        sketch.sketchCurves._items.append(curve)
        collection._items.append(curve)


def go_stale(*entities, attrs=("name", "parentComponent")):
    """Make `entities` stop answering their IDENTITY reads. MEASUREMENT reads (volume, faces,
    boundingBox, vertices) are left alone - those are what a post-mutation effect check counts on.

    This is a deliberate WORST CASE, not measured platform behaviour: a held target body was
    measured STILL answering parentComponent after a direct splitBodyFeatures.add. What it pins is
    that a handler must not DEPEND on a post-mutation identity read - a body the feature consumed
    outright has no such guarantee, and the dependency is invisible while every proxy stays alive.

    Call it from a feature fake's add(), after the canned effect lands: a payload key or an error
    clause that reads .name/.parentComponent AFTERWARDS then reads as unavailable, which is what
    forces the handler to capture it BEFORE."""
    for e in entities:
        for attr in attrs:
            if hasattr(e, attr):
                delattr(e, attr)


def install(mod, design, *, cast_design=True, object_collection=True):
    """Wire `design` into a tool module under both seams (see the dual-seam note above).

    Patches: mod.app (+ mod._common.app), and — when present — mod._inputs._common.design /
    target_component, plus adsk.fusion.Design.cast (pass-through for our design) and
    adsk.core.ObjectCollection.create (a minimal counted collection). All of these are reverted to
    pristine after each test by the autouse fixture, so the patch can't leak.

    Returns `design` for convenience (e.g. `design = install(mod, make_design(...))`).
    """
    import adsk.fusion
    import adsk.core

    comp = getattr(design, "rootComponent", None)
    target = lambda _d=None: getattr(design, "activeComponent", None) or comp

    mod.app = types.SimpleNamespace(activeProduct=design)
    # The tool's own seam (it imported _common; some import `target_component` bare too).
    if hasattr(mod, "_common"):
        mod._common.app = mod.app
        mod._common.design = lambda: design
        mod._common.target_component = target
    # The input-kinds seam (BodyRef/PlaneRef/AxisRef/GeometryHandle resolve through _inputs._common).
    if hasattr(mod, "_inputs") and hasattr(mod._inputs, "_common"):
        mod._inputs._common.design = lambda: design
        mod._inputs._common.target_component = target
    # A tool that imported `target_component`/`design` bare as module globals (e.g. model_fillet_chamfer).
    if hasattr(mod, "target_component"):
        mod.target_component = target
    if hasattr(mod, "design"):
        mod.design = lambda: design

    if cast_design:
        adsk.fusion.Design.cast = lambda x: x if x is design or isinstance(x, MakeDesign) else None
    if object_collection:
        adsk.core.ObjectCollection.create = staticmethod(_make_object_collection)
    return design


class _FakeObjectCollection:
    """ObjectCollection: add() ANSWERS whether the collection took the object (live returns a bool),
    so a tool that reads that answer sees a real one. `refuse` holds the objects it rejects - the
    silent-False case a collection-building tool has to report rather than run on an empty
    collection."""
    def __init__(self, refuse=()):
        self._items = []
        self._refuse = list(refuse)
    def add(self, x):
        if any(x is r for r in self._refuse):
            return False
        self._items.append(x)
        return True
    @property
    def count(self):
        return len(self._items)
    def __iter__(self):
        return iter(self._items)
    def item(self, i):
        return self._items[i]


def _make_object_collection(refuse=()):
    return _FakeObjectCollection(refuse)


def payload(result):
    """The success JSON body of a tool result; asserts it is NOT an error first."""
    assert result["isError"] is False, result
    return json.loads(result["content"][0]["text"])


def error_message(result):
    """Assert a tool result IS an error and return its message (for guard assertions)."""
    assert result["isError"] is True, result
    return result["message"]


def assert_no_active_design(mod, handler, **valid_kwargs):
    """A write/read tool that needs a design must return a clean 'no active design' error (not crash)
    when there is none. Point both seams at None, call the handler with otherwise-valid args, and
    assert the error mentions the design. Surfaces tools that skip the guard and NPE instead."""
    if hasattr(mod, "_common"):
        mod._common.design = lambda: None
    if hasattr(mod, "_inputs") and hasattr(mod._inputs, "_common"):
        mod._inputs._common.design = lambda: None
    res = handler(**valid_kwargs)
    msg = error_message(res).lower()
    assert "design" in msg or "document" in msg, res


def assert_unknown_units(handler, units_param="units", **valid_kwargs):
    """A tool taking a unit must reject an unknown one with a clear error (naming the unit), not
    silently scale by a bogus factor. Pass the other valid args; this sets units='furlong'."""
    res = handler(**{**valid_kwargs, units_param: "furlong"})
    msg = error_message(res).lower()
    assert "unit" in msg, res
