# Copyright (c) Fusion-Essentials contributors
# Dual-licensed under the MIT and Apache-2.0 licenses; see LICENSE-MIT and LICENSE-APACHE.

"""The step engine and the receipt: what runs the acts, and what stamps the run.

`run_steps` is the ONE (tool, args, expect, save) engine every live harness judges its steps
through, so the status vocabulary cannot fork; `judged_steps` is the list that pairs positionally
with its rows. `run` walks the acts, takes each one's narrative or fallback lane, and turns the
rows into the per-tool ledger. `source_hash`/`write_verified`/`check` are the receipt: a green run
stamps VERIFIED_TOOLS.md with a hash of the tool source AND this harness, and `--check` recomputes
it offline.

Orchestration only - no step rows, no domain knowledge. The names a consumer patches (`call`,
`ACTS`, `STORY`, `source_hash`, ...) are read off the FACADE namespace through `verify_core.facade`
when a run starts, never bound here at import.
"""

import hashlib
import json
import os
import re
import time

from verify_core import (
    NOTE_MAX, Parked, REFUSAL_NOTE_MAX, SRC_ROOT, STEP_SLEEP_S, VERIFIED, _HERE,
    _RUNTIME_BUDGET_S, _Refusal, _SHELL_TIMEOUT_S, _leaves_no_row, _unparked, facade,
    predicate_kind)


def source_hash(root=None):
    """SHA-256 over every .py under commands/mcpServer/ PLUS this harness and its siblings under
    tests/live/ - the receipt key binding a green run to the exact tool source AND the exact
    predicates/exclusions it was judged by (a weakened predicate or a tool quietly moved into
    EXCLUDED must invalidate the receipt, not ride under it). Relative paths are normalized to
    '/' and CRLF to LF so the digest is identical across OS and git line-ending config;
    __pycache__ is skipped."""
    root = root or SRC_ROOT
    entries = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for fn in filenames:
            if fn.endswith(".py"):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, root).replace(os.sep, "/")
                entries.append((rel, full))
    if root == SRC_ROOT:      # a custom root (the offline tests') hashes only itself
        for fn in sorted(os.listdir(_HERE)):
            if fn.endswith(".py"):
                entries.append(("tests_live/" + fn, os.path.join(_HERE, fn)))
    hasher = hashlib.sha256()
    for rel, full in sorted(entries):
        with open(full, "rb") as fh:
            content = fh.read().replace(b"\r\n", b"\n")
        hasher.update(rel.encode("utf-8") + b"\0" + content + b"\0")
    return hasher.hexdigest()


_STAMP_RE = re.compile(r"^Stamp: source ([0-9a-f]{64}) \| Fusion (\S+) \| verified (\S+)",
                       re.MULTILINE)


def write_verified(ledger, fusion_version, stamp_date, src_hash, path=None, notes=None,
                   act_modes=None):
    """Write the tracked receipt. Called only on a run with zero FAIL/blocked/pass* steps. 'notes'
    maps a driven tool to its shot-list step text (the ledger doubles as the demo's shot list) - a
    third column, empty when absent so the two-column stamp/count contract is unchanged.
    'act_modes' lists (act, narrative|fallback) - a machine-readable column, so a fallback-heavy
    run is visible without reading prose."""
    notes = notes or {}
    n_cov = sum(1 for _, s in ledger if s == "covered")
    # 'called' and 'called (<parked reason>)' are the SAME bucket - the reason is rendering, not a
    # third state, so the count line cannot drift from the table when a step is parked.
    n_called = sum(1 for _, s in ledger if s == "called" or s.startswith("called ("))
    n_pend = sum(1 for _, s in ledger if s.startswith("PENDING"))
    n_ref = sum(1 for _, s in ledger if s.startswith("refusals-only"))
    n_skip = len(ledger) - n_cov - n_called - n_pend - n_ref
    lines = [
        "# Live tool verification (generated by tool_verify.py - do not edit)",
        "",
        "This is a FIVE-BUCKET ledger, not a clean bill of health. It does NOT claim every tool",
        "is verified - the count line below is authoritative, and the per-tool table says which",
        "bucket each tool is in:",
        "",
        "- covered: a live step drove the tool this run and its expectation was a VALUE PREDICATE -",
        "  the step read keys off the ok payload (a delta, a count read back off the feature, a",
        "  verified flag) and those values held. This is the bucket that carries evidence.",
        "- called: every passing step for this tool was a bare 'ok' expectation - the call came back",
        "  without an error and NOTHING in the payload was read. What that proves is whatever the",
        "  tool's own post-write verification refuses on, and no more. Read a called row as",
        "  'called, and did not fail' - it is the queue for the next predicate tranche. A",
        "  'called (reason)' row is PARKED: a step deliberately held at a bare 'ok', the reason",
        "  naming what blocks its value predicate.",
        "- refusals-only: every step that ran was a deliberate guard refusal - the guards are",
        "  proven, but NO effect was produced or read back. Not covered; the create/act path",
        "  still needs a real step or a recorded gate reason.",
        "- skipped(reason): deliberately NOT driven unattended (cloud / interactive / irreversible",
        "  tier), each row naming why. Not verified - excused.",
        "- pending: no step drives it yet. UNVERIFIED, not known-good - it has never run in this",
        "  sweep. Shrinking this bucket means scripting a real step, not relabelling it.",
        "",
        "The stamp's source hash binds this run to the exact `commands/mcpServer/` tree AND the",
        "tests/live/ harness (steps, predicates, exclusions) it was judged by: `--check`",
        "recomputes the hash and fails on any difference, so a green suite cannot ride on a live",
        "run that never saw the current code or a weakened predicate. Only a run with zero",
        "FAIL/blocked/pass* steps rewrites this file.",
        "",
        "Stamp: source {0} | Fusion {1} | verified {2}".format(src_hash, fusion_version, stamp_date),
        "",
        "{0} covered / {1} called / {2} refusals-only / {3} skipped(reason) / {4} pending".format(
            n_cov, n_called, n_ref, n_skip, n_pend),
    ]
    if act_modes:
        lines += ["", "| act | mode |", "|---|---|"]
        lines += ["| {0} | {1} |".format(a, m) for a, m in act_modes]
    lines += [
        "",
        "| tool | status | step (the demo's shot list) |",
        "|---|---|---|",
    ]
    for tool, status in ledger:
        lines.append("| {0} | {1} | {2} |".format(
            tool, status.replace("|", "/"), notes.get(tool, "").replace("|", "/")))
    with open(path or VERIFIED, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return path or VERIFIED


def check(root=None, verified_path=None):
    """The receipt gate: drives nothing, needs no Fusion. Exit 0 = the last green live run saw
    exactly this tool source; 1 = no receipt, or the source changed since that run."""
    source_hash = facade("source_hash")
    path = verified_path or VERIFIED
    if not os.path.exists(path):
        print("VERIFIED_TOOLS.md does not exist - run tool_verify.py once against live Fusion.")
        return 1
    with open(path, encoding="utf-8") as fh:
        m = _STAMP_RE.search(fh.read())
    if not m:
        print("VERIFIED_TOOLS.md has no stamp line - regenerate it (run tool_verify.py).")
        return 1
    stamped_hash, stamped_version, stamped_date = m.groups()
    current = source_hash(root)
    if current != stamped_hash:
        print("tool source changed since the last live verification ({0}, Fusion {1}) -"
              .format(stamped_date, stamped_version))
        print("re-run with Fusion up: py -3 tests/live/tool_verify.py")
        return 1
    print("live verification current: source matches the green run of {0} (Fusion {1})"
          .format(stamped_date, stamped_version))
    return 0


def _shoot(label, out_dir, seq):
    """Capture the CURRENT view to out_dir. Used by --shots after each framing row: the frame ratio
    being arithmetically right is not evidence the view shows the thing - only looking is. Returns
    the path written, or None (a shot that fails is never worth failing the sweep over)."""
    call = facade("call")
    safe_label = re.sub(r"[^A-Za-z0-9_.-]", "_", label)[:60]
    path = os.path.join(out_dir, f"{seq:04d}_{safe_label}.png")
    is_error, _ = call("view_screenshot", {"width": 640, "height": 460, "file_path": path})
    return None if is_error else path


def run_steps(steps, ctx, trace=False, sleep_s=STEP_SLEEP_S, on_result=None, timings=None,
              shots_dir=None):
    """The ONE (tool, args, expect, save) step engine - every live harness judges its steps here,
    so the status vocabulary cannot fork: pass / pass* / expected-refusal / FAIL / blocked.
    'pass*' means a passing step whose saved-value extraction failed - a payload-shape mismatch
    that BLOCKS a green receipt/run in every consumer, never a quiet pass. A failing step keeps
    NOTE_MAX characters of its payload (the keys that diagnose it sit late), a passing refusal
    REFUSAL_NOTE_MAX. Yields nothing early:
    returns the full row list; 'on_result' (tool, status, note) fires per step for a consumer
    that prints as it goes. 'timings', when given, accumulates {tool: (seconds, calls)} over the
    wire calls - the sweep runs against a 600 s shell ceiling, so where its time goes has to be
    measurable rather than guessed at."""
    call = facade("call")
    rows = []
    for step in steps:
        if _leaves_no_row(step):
            # a showcase beat: hold the view, judge nothing, and leave no row - it is not a tool.
            time.sleep(step[1]["seconds"])
            continue
        tool, args, expect, save = step
        # A Parked wrapper carries a ledger reason, never a judgement: the step is judged by the
        # expectation inside it exactly as if that expectation had been passed bare.
        expect = _unparked(expect)
        try:
            arguments = args(ctx) if callable(args) else dict(args)
        except KeyError as e:
            rows.append((tool, "blocked", str(e)))
            if on_result:
                on_result(*rows[-1])
            continue
        if trace:
            # flushed per step so a hard Fusion crash still names its killer in the log
            print(f"    -> {tool} {json.dumps(arguments)[:120]}", flush=True)
        t0 = time.time()
        is_error, payload = call(tool, arguments)
        if timings is not None:
            spent, count = timings.get(tool, (0.0, 0))
            timings[tool] = (spent + time.time() - t0, count + 1)
        if isinstance(expect, _Refusal):
            # a refusal whose WORDS are the assertion: the error must carry every fragment, so a
            # guard refusing for another reason fails the row instead of passing as "refused".
            if not is_error:
                status, note = "FAIL", f"expected a refusal, got ok: {str(payload)[:NOTE_MAX]}"
            else:
                absent = expect.missing(str(payload))
                if absent:
                    status, note = "FAIL", f"refusal missing {absent}: {str(payload)[:NOTE_MAX]}"
                else:
                    status, note = "expected-refusal", str(payload)[:REFUSAL_NOTE_MAX]
        elif callable(expect):
            # a VALUE PREDICATE on an ok result: call success is not enough - the payload
            # must satisfy the check (grip contact, machine assignment, rest-pose honesty).
            if is_error:
                status, note = "FAIL", str(payload)[:NOTE_MAX]
            else:
                try:
                    good = bool(expect(payload))
                except Exception as e:
                    good, payload = False, f"predicate raised: {e}"
                status, note = ("pass", "") if good else ("FAIL", str(payload)[:NOTE_MAX])
        elif expect == "ok" and not is_error:
            status, note = "pass", ""
        elif expect == "refused" and is_error:
            status, note = "expected-refusal", str(payload)[:REFUSAL_NOTE_MAX]
        else:
            status, note = "FAIL", str(payload)[:NOTE_MAX]
        if status == "pass" and save is not None and not is_error:
            key, extract = save
            try:
                ctx[key] = extract(payload)
            except Exception as e:
                status, note = "pass*", f"saved-value extraction failed: {e}"
        rows.append((tool, status, note))
        if on_result:
            on_result(*rows[-1])
        if shots_dir and tool == "view_set" and status == "pass" and arguments.get("focus"):
            f = arguments["focus"]
            _shoot("-".join(f) if isinstance(f, list) else str(f), shots_dir, len(rows))
        if sleep_s:
            time.sleep(sleep_s)
    return rows


def judged_steps(steps):
    """The steps run_steps produces a ROW for, in order - which is what pairs positionally with
    those rows. A row-less step (today only a _dwell, which holds the view and is judged by
    nothing) would otherwise shift the pairing: every expectation after it gets credited to a LATER
    step's tool, so a bare "ok" reads as covered and a value predicate is lost."""
    return [s for s in steps if not _leaves_no_row(s)]


def _precondition_holds(pre):
    """Run an act's precondition READ; True when it returns without error (the geometry the act's
    narrative consumes exists). A False routes the act to its scratch fallback."""
    tool, args = pre
    is_error, _ = facade("call")(tool, args)
    return not is_error


def run(write_json, keep_open=False, trace=False, shots_dir=None):
    # The wire reads, the act program and the ledger tables as the FACADE holds them at the moment
    # the run starts - see verify_core.facade for why they are not this module's own globals.
    health_gate, registered_tools = facade("health_gate"), facade("registered_tools")
    source_hash, write_verified = facade("source_hash"), facade("write_verified")
    poll_generation = facade("poll_generation")
    ACTS, POLL_AFTER, STORY, EXCLUDED = (facade("ACTS"), facade("POLL_AFTER"), facade("STORY"),
                                         facade("EXCLUDED"))
    health = health_gate()
    print(f"server ok: {health.get('server')} v{health.get('version', '?')}")
    all_tools = registered_tools()

    ctx, rows, notes, act_modes = {}, [], {}, []
    timings, act_seconds, run_started = {}, [], time.time()
    # the tools whose PASSING step read a value off the payload - run_steps returns exactly one row
    # per step, in order, so a row is paired back with the expectation that judged it.
    valued = set()
    # tool -> the reason a Parked step held it at a bare "ok", for the ledger's status column.
    parked = {}
    for name, pre, narrative, fallback in ACTS:
        mode, steps = "narrative", narrative
        if pre is not None and fallback is not None and not _precondition_holds(pre):
            mode, steps = "fallback", fallback
        act_modes.append((name, mode))
        print(f"\n-- {name} [{mode}] --")
        act_started = time.time()
        if keep_open and name == "FINALE":
            steps = [s for s in steps if s[0] != "doc_close"]
        # judged_steps, not the act's raw list, is what pairs with the rows below - see its
        # docstring for what a dwell does to the pairing.
        for step, (tool, status, note) in zip(judged_steps(steps),
                                              run_steps(steps, ctx, trace=trace, timings=timings,
                                                        shots_dir=shots_dir)):
            rows.append((tool, status, note))
            if status in ("pass", "pass*") and predicate_kind(step[2]) == "value":
                valued.add(tool)
            if status in ("pass", "pass*") and isinstance(step[2], Parked):
                parked[tool] = step[2].reason
            if status in ("pass", "pass*", "expected-refusal"):
                story = STORY.get(tool, "")
                notes[tool] = (story + " (fallback fixture)").strip() if mode == "fallback" else story
        if name in POLL_AFTER:
            poll_generation(rows, notes, POLL_AFTER[name][mode], valued=valued)
        act_seconds.append((name, time.time() - act_started))
    if keep_open:
        print("\n--keep-open: the story document is left open for inspection.")

    # covered demands at least one step that PRODUCED something (pass/pass*): a tool whose every
    # step is an expected-refusal exercised only its guards - no effect existed to read back, so
    # calling that "covered" would let the legend lie. Those rows get their own bucket.
    # covered vs called splits the produced-something set again: covered means a value predicate
    # read the effect off the payload, called means every passing step was a bare "ok".
    passed = {t for t, s, _ in rows if s in ("pass", "pass*")}
    refused_only = {t for t, s, _ in rows if s == "expected-refusal"} - passed
    ledger = []
    for tool in all_tools:
        if tool in valued:
            ledger.append((tool, "covered"))
        elif tool in passed:
            # a parked tool stays in the CALLED bucket and carries why it was held there, so the
            # reason is on the receipt instead of in a source comment only.
            ledger.append((tool, "called ({0})".format(parked[tool]) if tool in parked else "called"))
        elif tool in refused_only:
            ledger.append((tool, "refusals-only: every step is a guard refusal - no effect was "
                                 "produced or read back this run"))
        elif tool in EXCLUDED:
            ledger.append((tool, f"skipped: {EXCLUDED[tool]}"))
        else:
            ledger.append((tool, "PENDING (no step yet)"))

    print(f"\n== step results ({len(rows)}):")
    for tool, status, note in rows:
        print(f"  {status:18} {tool:28} {note}")
    n_cov = sum(1 for _, s in ledger if s == "covered")
    n_called = sum(1 for _, s in ledger if s == "called" or s.startswith("called ("))
    n_pend = sum(1 for _, s in ledger if s.startswith("PENDING"))
    n_ref = sum(1 for _, s in ledger if s.startswith("refusals-only"))
    n_skip = len(ledger) - n_cov - n_called - n_pend - n_ref
    print(f"\n== ledger: {n_cov}/{len(ledger)} covered, {n_called} called (bare ok), "
          f"{n_ref} refusals-only, {n_skip} skipped(reason), {n_pend} pending")
    for tool, s in ledger:
        if s != "covered":
            print(f"  {tool:32} {s}")

    # WHERE THE SECONDS WENT. The sweep has to finish inside a 600 s shell call, so the run
    # publishes its own budget rather than leaving the next person to guess: the total, the slowest
    # acts, and the tools that spent the most wire time - with a per-call average, which is what
    # separates a tool that is CALLED a lot from a tool that is SLOW.
    elapsed = time.time() - run_started
    print(f"\n== elapsed: {elapsed:.0f}s for {len(rows)} steps "
          f"({STEP_SLEEP_S * len(rows):.0f}s of it the inter-step sleep)")
    for nm, secs in sorted(act_seconds, key=lambda r: -r[1])[:5]:
        print(f"  {secs:7.1f}s  {nm}")
    print("  slowest tools (total / calls / per call):")
    for tool, (secs, count) in sorted(timings.items(), key=lambda kv: -kv[1][0])[:8]:
        print(f"  {secs:7.1f}s  {count:4} x {secs / max(count, 1):5.2f}s  {tool}")
    # THE BUDGET IS PART OF THE RESULT, not a note for the next person. Every agent runs this through
    # a shell tool that is killed at 600 s, so a sweep that creeps past the budget is one nobody can
    # run - and a timeout kills the process without a receipt, which reads as a broken tool rather
    # than a slow sweep. Failing here turns that into a named result with the act breakdown above it.
    over_budget = elapsed > _RUNTIME_BUDGET_S
    if over_budget:
        print(f"\nOVER BUDGET: {elapsed:.0f}s exceeds the {_RUNTIME_BUDGET_S:.0f}s ceiling "
              f"({_SHELL_TIMEOUT_S:.0f}s is where the shell tool kills it). The act and tool "
              f"breakdowns above name where it went - cut there, or drop a dwell.")

    n_narr = sum(1 for _, m in act_modes if m == "narrative")
    n_fb = sum(1 for _, m in act_modes if m == "fallback")
    print(f"\n== acts: {n_narr} narrative / {n_fb} fallback (of {len(act_modes)})")
    for nm, m in act_modes:
        print(f"  {m:10} {nm}")

    # pass* blocks the receipt: the payload did not carry a key the step contract expected - a
    # payload-shape mismatch is a real signal, not a pass.
    fails = [r for r in rows if r[1] in ("FAIL", "blocked", "pass*")]
    if fails or over_budget:
        print("\nVERIFIED_TOOLS.md NOT rewritten - resolve the FAIL/blocked/pass* steps first.")
    else:
        src_hash = source_hash()
        stamp_date = time.strftime("%Y-%m-%d")
        fusion_version = ctx.get("fusion_version", "?")
        print("\nwrote {0} (stamp: source {1}..., Fusion {2}, {3})".format(
            write_verified(ledger, fusion_version, stamp_date, src_hash, notes=notes,
                           act_modes=act_modes),
            src_hash[:12], fusion_version, stamp_date))
    if write_json:
        results_dir = os.path.join(_HERE, "results")
        os.makedirs(results_dir, exist_ok=True)
        path = os.path.join(results_dir, f"verify-{time.strftime('%Y%m%d-%H%M%S')}.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({"steps": rows, "ledger": ledger, "acts": act_modes, "server": health}, fh, indent=2)
        print(f"\nwrote {path}")
    return 1 if (fails or over_budget) else 0
